// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKxaakb0d9-56KQP7y33-N9koz6Dpr-S8',
    appId: '1:848607557123:web:1bb54cfdf79c04e5a78036',
    messagingSenderId: '848607557123',
    projectId: 'my-new-app-naona-20260523',
    authDomain: 'my-new-app-naona-20260523.firebaseapp.com',
    storageBucket: 'my-new-app-naona-20260523.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxLnlQCq9WMPr7CAgpptuffggUHBJwcH0',
    appId: '1:848607557123:android:a258123325cd9371a78036',
    messagingSenderId: '848607557123',
    projectId: 'my-new-app-naona-20260523',
    storageBucket: 'my-new-app-naona-20260523.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAq5-7-qcwWtKlg8Yr07csgJvmN1UzmqAU',
    appId: '1:848607557123:ios:716fbc4db30fe514a78036',
    messagingSenderId: '848607557123',
    projectId: 'my-new-app-naona-20260523',
    storageBucket: 'my-new-app-naona-20260523.firebasestorage.app',
    androidClientId:
        '848607557123-g30pgdcju2i13pirjksmjdsh6bag6n09.apps.googleusercontent.com',
    iosClientId:
        '848607557123-ep6vgeegut56sv1ftrnav5dv4ojejip7.apps.googleusercontent.com',
    iosBundleId: 'com.example.myNewApp',
  );
}
